restart
needsPackage "NormalToricVarieties"


-- Here, we verify that any exponent (a1,...,a6) appearing in F1.F2.F3 satisfies the relations a1 + a4 = a2 + a3 + a5 + a6 = 0.
T = QQ[x_1..x_6, y_1..y_6]/ideal(apply(6, i->x_(i+1)*y_(i+1)-1)) -- coordinate ring of a torus
F1 = x_1*x_2*x_3*y_5*y_6 + x_1*x_2*y_6 + x_2*x_3*x_4*y_5*y_6 + x_1 + x_4
F2 = y_2*x_5*x_6 + x_2 + x_3 + x_5 + x_6
F3 = y_1*y_2 + y_1*y_2*y_3*x_6 + y_1*y_2^2*y_3*x_5*x_6 + y_3*y_4 + y_2*y_3*y_4*x_5 + y_2*y_4 + y_2*y_3*y_4*x_6 + y_2^2*y_3*y_4*x_5*x_6

E = exponents(F1*F2*F3)
vv = E/(e -> e_{0,1,2,3,4,5} - e_{6,7,8,9,10,11}) -- all exponents appearing in F1*F2*F3
ker matrix vv -- we get two relations


-- Next, we verify that the Newton polytope of G1.G2.G3 is a reflexive 4-dimensional polytope in R^4 and hence contains the origin in its interior.
T = QQ[u_1..u_4, v_1..v_4]/ideal(apply(4, i->u_(i+1)*v_(i+1)-1)) -- coordinate ring of a torus

G1 = u_1*u_2*u_3*v_4 + u_1*u_2 + u_2*u_3*v_4 + u_1 + 1
G2 = u_4*v_2 + u_2 + u_3 + u_4 + 1
G3 = v_1*v_2 + v_1*v_2*v_3 + v_1*v_2^2*v_3*u_4 + v_3 + v_2*v_3*u_4 + v_2 + v_2*v_3 + v_2^2*v_3*u_4
E = exponents(G1*G2*G3)/(e -> e_{0,1,2,3} - e_{4,5,6,7})
NewtonPolytope = convexHull transpose matrix E
dim NewtonPolytope
isReflexive NewtonPolytope


-- Next, we find the degree of the discriminant locus of the compactified pencil.
S = QQ[u_0..u_4, t_0, t_1] -- homogenous coordinate ring of the ambient space P^4 x P^1 of the pencil.

Q = u_1*u_2^3*u_3*u_4
P = sub(G1*G2*G3*sub(Q,T), S)
pencil = homogenize(t_0*P - t_1*Q, u_0)

J = saturate((ideal(apply(5, i -> diff(u_i, pencil))) + ideal(pencil)), ideal(sub(pencil, {t_0=>0, t_1=>1}), sub(pencil, {t_0=>1, t_1=>0})));
J = saturate((ideal(apply(5, i -> diff(u_i, pencil))) + ideal(pencil)), ideal(sub(pencil, {t_0=>0, t_1=>1}), sub(pencil, {t_0=>1, t_1=>0})));
discriminantLocus = ker map(S/J, QQ[t_0,t_1], matrix{{(t_0)_S,(t_1)_S}})
degree discriminantLocus -- 5


-- Next, we compute the we compute the first 30 coefficients of the pricipal period and then solve the resulting linear equations in the indeterminates to compute D.
A = (n) -> (sub(last terms((G1*G2*G3)^n), ZZ))
fullCoefficientList = (f) -> (flatten entries basis(first degree f, ring f))/(m -> coefficient(m, f))

C = QQ[theta][z][c_(0,0)..c_(4,4)] -- polynomial ring generated by the indeterminates in the operator
P = apply(5, i -> ((n) -> c_(i,0) + c_(i,1)*n + c_(i,2)*n^2 + c_(i,3)*n^3 + c_(i,4)*n^4))
a = apply(30, n -> A(n)) -- {1, 11, 559, 42923, 3996751, 416148761, 46607742091, 5494953548459, 673006663951183, 84887862132737261, 10960384987436995309, 1442356991928315362009, 192832695330486199076011, 26126080107002322789528197, 3580244300364122205875141059, 495479786625880934937914634923, 69162655828624756613259127413583, 9727572509392284295879636850257397, 1377381556948991019969319851097307449, 196205005200557561701838965894739484173, 28100121377101502685730665632369681575501, 4044110160459883787873182119892985572686491, 584601469043175840836590052260070394799090249, 84849655957130647949320411024058657880757106393, 12360782465873293068286987426696670402529985934251, 1806832316206138774124773283611717478292644188023761, 264942213137681627075675516978815778608378155810717721, 38962261290115404796146808876912054469285742008013154949, 5745212385530444751633927205463072242404418125592994072803, 849289353192324671490430136372759715589051246268899318079261}; -- the first 30 coefficients

eqns = apply(25, n -> {a_n*P_0(n) + a_(n+1)*P_1(n+1) + a_(n+2)*P_2(n+2) + a_(n+3)*P_3(n+3) + a_(n+4)*P_4(n+4), -49*a_(n+5)*(n+5)^4}); -- affine realtions among the indeterminates
eqnsAsMat = matrix(eqns/(e -> fullCoefficientList e_0))
rank eqnsAsMat
targetAsMat = transpose matrix{eqns/(e -> e_1)}
solns = inverse(eqnsAsMat)*targetAsMat -- {121, 484, 726, 484, 121,616, 5005, 14784, 19558, 10010, -1806, -10731, -26511, -38514, -32126,-896, -1337, 13260, 40708, 28723,-539, -4067, -11781, -15428, -7945}

D = sub(z^5*P_0(theta) + z^4*P_1(theta) + z^3*P_2(theta) + z^2*P_3(theta) + z*P_4(theta) + 49*theta^4, transpose solns)
DY = 49*theta^4-7*z*(1135*theta^4+2204*theta^3+1683*theta^2+581*theta+77)+z^2*(28723*theta^4+40708*theta^3+13260*theta^2-1337*theta-896)-z^3*(32126*theta^4+38514*theta^3+26511*theta^2+10731*theta+1806)+77*z^4*(130*theta^4+254*theta^3+192*theta^2+65*theta+8)+121*z^5*((theta+1)^4)
D == DY -- true